# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Jiewo\Folder\Done\2023_fall\intro_of_information_security\simple_des\Simple_DES\ui\crack.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CrackWindow(object):
    def setupUi(self, CrackWindow):
        CrackWindow.setObjectName("CrackWindow")
        CrackWindow.resize(800, 428)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CrackWindow.sizePolicy().hasHeightForWidth())
        CrackWindow.setSizePolicy(sizePolicy)
        CrackWindow.setMinimumSize(QtCore.QSize(800, 428))
        CrackWindow.setMaximumSize(QtCore.QSize(800, 428))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon/lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CrackWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(CrackWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(0, 0, 821, 451))
        self.main_frame.setAutoFillBackground(False)
        self.main_frame.setStyleSheet("QFrame {\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"}\n"
"\n"
"")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setLineWidth(1)
        self.main_frame.setObjectName("main_frame")
        self.content_frame = QtWidgets.QFrame(self.main_frame)
        self.content_frame.setGeometry(QtCore.QRect(260, 30, 511, 371))
        self.content_frame.setStyleSheet("QLineEdit {\n"
"    border-radius:10px;\n"
"    background-color:rgb(240, 240, 240);\n"
"    padding-left:10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(240, 240, 240);\n"
"}\n"
"\n"
"#content_frame {\n"
"    border:3px solid rgb(170, 170, 255);\n"
"}\n"
"\n"
"QFrame {\n"
"    border-radius:20px;\n"
"}")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.plain_text_label = QtWidgets.QLabel(self.content_frame)
        self.plain_text_label.setGeometry(QtCore.QRect(40, 20, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.plain_text_label.setFont(font)
        self.plain_text_label.setObjectName("plain_text_label")
        self.encrypted_text_label = QtWidgets.QLabel(self.content_frame)
        self.encrypted_text_label.setGeometry(QtCore.QRect(40, 80, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.encrypted_text_label.setFont(font)
        self.encrypted_text_label.setObjectName("encrypted_text_label")
        self.crack_button = QtWidgets.QPushButton(self.content_frame)
        self.crack_button.setGeometry(QtCore.QRect(130, 290, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.crack_button.setFont(font)
        self.crack_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.crack_button.setMouseTracking(False)
        self.crack_button.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    background-color:rgb(85, 0, 127);\n"
"    border-radius:18px;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color:rgb(170, 170, 255);\n"
"}\n"
"\n"
"")
        self.crack_button.setObjectName("crack_button")
        self.plain_text_input = QtWidgets.QLineEdit(self.content_frame)
        self.plain_text_input.setGeometry(QtCore.QRect(240, 20, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.plain_text_input.setFont(font)
        self.plain_text_input.setStyleSheet("")
        self.plain_text_input.setText("")
        self.plain_text_input.setReadOnly(False)
        self.plain_text_input.setClearButtonEnabled(False)
        self.plain_text_input.setObjectName("plain_text_input")
        self.char_button = QtWidgets.QRadioButton(self.content_frame)
        self.char_button.setGeometry(QtCore.QRect(40, 180, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.char_button.setFont(font)
        self.char_button.setObjectName("char_button")
        self.choose_mode_group = QtWidgets.QButtonGroup(CrackWindow)
        self.choose_mode_group.setObjectName("choose_mode_group")
        self.choose_mode_group.addButton(self.char_button)
        self.binary_button = QtWidgets.QRadioButton(self.content_frame)
        self.binary_button.setGeometry(QtCore.QRect(40, 220, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.binary_button.setFont(font)
        self.binary_button.setObjectName("binary_button")
        self.choose_mode_group.addButton(self.binary_button)
        self.crack_result = QtWidgets.QLabel(self.content_frame)
        self.crack_result.setGeometry(QtCore.QRect(40, 130, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.crack_result.setFont(font)
        self.crack_result.setObjectName("crack_result")
        self.key_result = QtWidgets.QTextEdit(self.content_frame)
        self.key_result.setGeometry(QtCore.QRect(240, 140, 241, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.key_result.setFont(font)
        self.key_result.setStyleSheet("QTextEdit {\n"
"    background-color:rgb(240, 240, 240);\n"
"    border-radius:10px;\n"
"    border:none;\n"
"}")
        self.key_result.setReadOnly(False)
        self.key_result.setObjectName("key_result")
        self.encrypted_text_input = QtWidgets.QLineEdit(self.content_frame)
        self.encrypted_text_input.setGeometry(QtCore.QRect(240, 80, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.encrypted_text_input.setFont(font)
        self.encrypted_text_input.setStyleSheet("")
        self.encrypted_text_input.setText("")
        self.encrypted_text_input.setReadOnly(False)
        self.encrypted_text_input.setClearButtonEnabled(False)
        self.encrypted_text_input.setObjectName("encrypted_text_input")
        self.menu_frame = QtWidgets.QFrame(self.main_frame)
        self.menu_frame.setGeometry(QtCore.QRect(30, 30, 211, 371))
        self.menu_frame.setStyleSheet("QPushButton {\n"
"    border-radius:10px;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color:rgb(210, 213, 255);\n"
"    border-radius:20px;\n"
"}\n"
"")
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.decryption_button = QtWidgets.QPushButton(self.menu_frame)
        self.decryption_button.setGeometry(QtCore.QRect(20, 90, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.decryption_button.setFont(font)
        self.decryption_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.decryption_button.setStyleSheet("QPushButton::hover {\n"
"    background-color:rgb(230, 230, 230)\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color:rgb(224, 220, 240)\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon/decryption.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.decryption_button.setIcon(icon1)
        self.decryption_button.setObjectName("decryption_button")
        self.encryption_button = QtWidgets.QPushButton(self.menu_frame)
        self.encryption_button.setGeometry(QtCore.QRect(18, 20, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.encryption_button.setFont(font)
        self.encryption_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.encryption_button.setStyleSheet("QPushButton::hover {\n"
"    background-color:rgb(230, 230, 230)\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    background-color:rgb(224, 220, 240)\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icon/encryption.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.encryption_button.setIcon(icon2)
        self.encryption_button.setObjectName("encryption_button")
        self.crack_button_2 = QtWidgets.QPushButton(self.menu_frame)
        self.crack_button_2.setGeometry(QtCore.QRect(20, 160, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.crack_button_2.setFont(font)
        self.crack_button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.crack_button_2.setStyleSheet("background-color:rgb(94, 0, 141);\n"
"color: white;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icon/spider.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.crack_button_2.setIcon(icon3)
        self.crack_button_2.setObjectName("crack_button_2")
        CrackWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CrackWindow)
        QtCore.QMetaObject.connectSlotsByName(CrackWindow)

    def retranslateUi(self, CrackWindow):
        _translate = QtCore.QCoreApplication.translate
        CrackWindow.setWindowTitle(_translate("CrackWindow", "Simple-DES"))
        self.plain_text_label.setText(_translate("CrackWindow", "Plain Text"))
        self.encrypted_text_label.setText(_translate("CrackWindow", "Encrypted Text"))
        self.crack_button.setText(_translate("CrackWindow", "Crack"))
        self.char_button.setText(_translate("CrackWindow", "string"))
        self.binary_button.setText(_translate("CrackWindow", "binary"))
        self.crack_result.setText(_translate("CrackWindow", "Crack Key"))
        self.key_result.setHtml(_translate("CrackWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.decryption_button.setText(_translate("CrackWindow", "  Decryption"))
        self.encryption_button.setText(_translate("CrackWindow", "  Encryption"))
        self.crack_button_2.setText(_translate("CrackWindow", "Crack"))
import ui.src.res_rc
